---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skippo-dev-landing-page
  labels:
    app: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: landing-page
          image: arseniskobelev/skippo-landing-page:8e08f47cc8fd008f7ebbd7d18d8133e41e2385e7
          ports:
            - containerPort: 3000
