---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: skippo-enwind-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /skippo/enwind
---
apiVerison: v1
kind: PersistentVolumeClaim
metadata:
  name: skippo-enwind-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard