---
apiVersion: v1
kind: Service
metadata:
  name: enwind
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.5.0.11
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: enwind
  type: LoadBalancer
  externalTrafficPolicy: Cluster